---
project_name: okapi_proj
application_name: okapi
server_user: ubuntu
git_repo: https://github.com/patrickspencer/okapi.git
system_packages:
  - git
  - nginx
  - gunicorn
  - postgresql
  - supervisor
  - postgresql-server-dev-all
  - python-pip
  - python-dev
  - python3-pip
  - python3-dev
  - python3-psycopg2

# db
db_user: "{{ application_name }}"
db_name: "{{ application_name }}_db"
db_password: password
db_host: localhost
db_port: 5432

# virtualenv
virtualenv_python_version: python3

# Project settings.
project_parent_dir: /var/www
project_path: "{{ project_parent_dir }}/{{ project_name }}"
application_path: "{{ project_path }}/{{ application_name }}"
virtualenv_path: "{{ project_path }}/.virtualenvs/okapi"
application_log_dir: "{{ project_path }}/okapi_logs"
application_log_file: "{{ project_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ application_path }}/requirements/production.txt"

# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps
gunicorn_log_file: "{{ application_log_dir }}/okapi_gunicorn.log"
gunicorn_sock_file: "{{ project_path }}/okapi_gunicorn.sock"

# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ application_path }}/server_static_files"
nginx_media_dir: "{{ application_path }}/media/"
nginx_server_name: "{{ inventory_hostname }}"

# Django environment variables.
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  DATABASE_HOST: "{{ db_host }}"
  DATABASE_PORT: "{{ db_port }}"
  ALLOWED_HOSTS: "{{ inventory_hostname }}"
