---

- name: Install system packages
  apt: pkg={{ item }} update-cache=yes
  with_items: "{{ system_packages }}"

- name: Clone git repo
  git: repo="{{ git_repo }}"
       dest=/home/ubuntu/okapi
       accept_hostkey=yes

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: Create the virtualenv
  command: virtualenv -p {{ virtualenv_python_version }} {{ virtualenv_path }}
           creates={{ virtualenv_path }}/bin/activate
