---

- name: Install system packages
  apt: pkg={{ item }} update-cache=yes
  with_items: "{{ system_packages }}"

- name: Clone git repo
  git: repo="{{ git_repo }}"
       dest=/home/ubuntu/okapi
       accept_hostkey=yes

- include: create_users_and_groups.yml
  tags: users_and_groups

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_django.yml
  tags: django

- include: setup_nginx.yml
  tags: nginx

- include: setup_supervisor.yml
  tags: supervisor
