---
- hosts: tag_Name_test2
  gather_facts: false
  remote_user: ubuntu
  become: true
  vars_files:
  - vars.yml

  pre_tasks:
  - name: 'install python2'
    raw: apt-get -y install python-simplejson

  tasks:
  - name: Install system packages
    apt: pkg={{ item }} update-cache=yes
    with_items: "{{ system_packages }}"


