---
- name: Provision a {{ project_name }} site
  hosts: tag_Name_test2
  remote_user: "{{ server_user }}"
  become: true
  vars_files:
  - vars.yml

  pre_tasks:
  - name: 'install python2'
    raw: apt-get -y install python-simplejson

  roles:
  - web
